# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rows',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('new_hire_id', models.CharField(max_length=30)),
                ('new_hire_name', models.CharField(max_length=30)),
                ('manager_id', models.CharField(max_length=30)),
                ('manager_name', models.CharField(max_length=30)),
            ],
        ),
    ]
